apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycloudapp
spec:
  replicas: 1
  # Stratégie de mise à jour sans interruption (Rolling Update)
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mycloudapp
  template:
    metadata:
      labels:
        app: mycloudapp
    spec:
      containers:
      - name: mycloudapp
        image: ghcr.io/coco-vig/mycloudapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        
        # Limites de consommation (CPU et RAM)
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
            
        # Sonde de vie (Si ça échoue, K8s redémarre le conteneur)
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
          
        # Sonde de disponibilité (Si ça échoue, K8s arrête d'envoyer du trafic web)
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
          
        env:
        - name: AZURE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: azure-connection-string